-- CreateTable
CREATE TABLE `credit_cards` (
    `CARD_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `CARD_NUMBER` VARCHAR(16) NOT NULL,
    `CARD_TYPE` ENUM('Visa', 'MasterCard', 'Amex', 'Discover') NOT NULL,
    `CREDIT_LIMIT` DECIMAL(10, 2) NOT NULL,
    `BALANCE` DECIMAL(10, 2) NULL DEFAULT 0.00,
    `INTEREST_RATE` DECIMAL(5, 2) NULL,
    `DUE_DATE` DATE NOT NULL,
    `STATUS` ENUM('Active', 'Blocked', 'Closed') NULL DEFAULT 'Active',

    UNIQUE INDEX `CARD_NUMBER`(`CARD_NUMBER`),
    INDEX `FK_CREDIT_CARDS`(`USER_ID`),
    PRIMARY KEY (`CARD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `payment_plan` (
    `PLAN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `CARD_ID` INTEGER NOT NULL,
    `CHOSEN_PLAN` ENUM('Lowest', 'Highest') NULL,
    `PROGRESS` INTEGER NOT NULL,
    `PLAN_START` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `EST_PLAN_FINISH` TIMESTAMP(0) NULL,

    INDEX `FK_PAYMENT_PLAN`(`USER_ID`),
    INDEX `FK_PAYMENT_PLAN1`(`CARD_ID`),
    PRIMARY KEY (`PLAN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `payments` (
    `PAYMENT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NULL,
    `CARD_ID` INTEGER NULL,
    `PAID` DECIMAL(10, 2) NOT NULL,
    `PAYMENT_DATE` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `PAYMENT_METHOD` ENUM('Transfer', 'Check', 'Credit', 'Cash', 'ACH') NOT NULL,
    `STATUS` ENUM('Pending', 'Completed', 'Failed') NULL DEFAULT 'Pending',

    INDEX `FK_PAYMENTS`(`USER_ID`),
    INDEX `FK_PAYMENTS1`(`CARD_ID`),
    PRIMARY KEY (`PAYMENT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `plaidtransaction` (
    `id` VARCHAR(191) NOT NULL,
    `transactionId` VARCHAR(191) NULL,
    `name` VARCHAR(191) NOT NULL,
    `amount` FLOAT NOT NULL,
    `date` DATETIME(0) NOT NULL,
    `account_id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NULL,
    `iso_currency_code` VARCHAR(10) NULL,
    `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `transactionId`(`transactionId`),
    INDEX `PlaidTransaction_userId_idx`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `security_log` (
    `LOG_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NULL,
    `ACTION` VARCHAR(255) NOT NULL,
    `LOG_TIME` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_SECURITY_LOG`(`USER_ID`),
    PRIMARY KEY (`LOG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `settlements` (
    `SET_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NULL,
    `CARD_ID` INTEGER NULL,
    `ORIGINAL_AMOUNT` DECIMAL(10, 2) NOT NULL,
    `SETTLED_AMOUNT` DECIMAL(10, 2) NOT NULL,
    `SET_DATE` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `STATUS` ENUM('Pending', 'Completed', 'Rejected') NULL DEFAULT 'Pending',

    INDEX `FK_SETTLEMENTS_CARD`(`CARD_ID`),
    INDEX `FK_SETTLEMENTS_USER`(`USER_ID`),
    PRIMARY KEY (`SET_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `transactions` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CARD_ID` INTEGER NULL,
    `TRANS_TYPE` ENUM('Purchase', 'Fee', 'Interest', 'Refund', 'Payment', 'Subscription') NOT NULL,
    `AMOUNT` DECIMAL(10, 2) NOT NULL,
    `MERCHANT` VARCHAR(100) NULL,
    `TRANS_DATE` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_TRANSACTIONS`(`CARD_ID`),
    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_session` (
    `SESSION_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NULL,
    `SESSION_TOKEN` VARCHAR(255) NOT NULL,
    `EXPIRES` TIMESTAMP(0) NOT NULL,

    UNIQUE INDEX `SESSION_TOKEN`(`SESSION_TOKEN`),
    INDEX `FK_USER_SESSION`(`USER_ID`),
    PRIMARY KEY (`SESSION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `userplaiditem` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `itemId` VARCHAR(191) NOT NULL,
    `encryptedAccessToken` TEXT NOT NULL,
    `createdAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `userId`(`userId`),
    UNIQUE INDEX `itemId`(`itemId`),
    INDEX `idx_userId`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PASS` VARCHAR(20) NOT NULL,
    `USER_LNAME` VARCHAR(15) NOT NULL,
    `USER_FNAME` VARCHAR(15) NOT NULL,
    `STREET` VARCHAR(25) NULL,
    `CITY` VARCHAR(20) NULL,
    `STATE` CHAR(2) NULL,
    `ZIP` VARCHAR(15) NULL,
    `GENDER` CHAR(1) NULL,
    `PHONE` VARCHAR(10) NULL,
    `EMAIL` VARCHAR(30) NULL,

    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `debt` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `balance` DECIMAL(10, 2) NOT NULL,
    `currentBalance` DECIMAL(10, 2) NOT NULL,
    `interestRate` DECIMAL(5, 2) NOT NULL,
    `minimumPayment` DECIMAL(10, 2) NOT NULL,
    `dueDate` DATE NOT NULL,
    `extraPayment` DECIMAL(10, 2) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `debt_userId_idx`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `credit_cards` ADD CONSTRAINT `FK_CREDIT_CARDS` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `payment_plan` ADD CONSTRAINT `FK_PAYMENT_PLAN` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `payment_plan` ADD CONSTRAINT `FK_PAYMENT_PLAN1` FOREIGN KEY (`CARD_ID`) REFERENCES `credit_cards`(`CARD_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `payments` ADD CONSTRAINT `FK_PAYMENTS` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `payments` ADD CONSTRAINT `FK_PAYMENTS1` FOREIGN KEY (`CARD_ID`) REFERENCES `credit_cards`(`CARD_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `security_log` ADD CONSTRAINT `FK_SECURITY_LOG` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `settlements` ADD CONSTRAINT `FK_SETTLEMENTS_CARD` FOREIGN KEY (`CARD_ID`) REFERENCES `credit_cards`(`CARD_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `settlements` ADD CONSTRAINT `FK_SETTLEMENTS_USER` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `transactions` ADD CONSTRAINT `FK_TRANSACTIONS` FOREIGN KEY (`CARD_ID`) REFERENCES `credit_cards`(`CARD_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `user_session` ADD CONSTRAINT `FK_USER_SESSION` FOREIGN KEY (`USER_ID`) REFERENCES `users`(`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
