import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { DebtProvider } from '../contexts/DebtContext';
import { Suspense } from 'react';
import { Footer } from "@/components/footer";

import "./globals.css";
import FloatingChatbot from "@/components/FloatingChatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
          suppressHydrationWarning
        >
          <DebtProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <div className="flex-grow">
                {children}
              </div>
              <Footer />
              <FloatingChatbot />
            </Suspense>
          </DebtProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}